[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dependency-ghost"
version = "0.1.0"
description = "AI-Hallucination Guard: Age-gating for Python dependencies"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Joseph Chu", email = "hotcupofjoe2013@gmail.com"}
]
dependencies=[
    "requests>=2.31.0"
]

[project.scripts]
# This turns your code into  a terminal command!
# Format: command_name = "package.module:function"
ghost = "ghost.checker:main"
ghost-init = "ghost.interceptor:generate_alias"
ghost-off = "ghost.interceptor:remove_alias"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
]
